path : data/graph_inhouse_example
result : results
index_folder : data/fold_inhouse_example
num_cls : 3
views: sag,cor,axi

# Training Settings
num_workers : 2
bs : 2
num_epoch : 20

# Optimizer settings
lr : 3.0e-5
weight_decay : 1.0e-4

# Model Settings
task : finetune_inhouse
input_size : 64
net : KGNet
