path : data/graph_mrnet_example/sag
result : results
index_folder : data/fold_mrnet_example
num_cls : 2
views: sag,sag,sag

# Training Settings
num_workers : 2
bs : 2
num_epoch : 100

# Optimizer settings
lr : 3.0e-4
weight_decay : 1.0e-4

# Model Settings
task : pretrain_mrnet
input_size : 64
net : KGNet
